if (global.debug){
	ini_open("savedata.ini")
	ini_write_real("achieves", "death_manimo", 0)
	ini_write_real("achieves", "death_valerix", 0)
	ini_write_real("achieves", "death_mathi", 0)
	ini_write_real("achieves", "death_sports", 0)
	ini_write_real("achieves", "death_ava", 0)
	ini_write_real("achieves", "death_pravi", 0)
	ini_write_real("achieves", "death_joetube", 0)
	ini_write_real("achieves", "death_dj", 0)
	ini_write_real("achieves", "death_jesse", 0)
	ini_write_real("achieves", "death_lydia", 0)
	ini_write_real("achieves", "death_a90", 0)
	ini_write_real("achieves", "complete_attic", 0)
	ini_write_real("achieves", "complete_wheatfield", 0)
	ini_write_real("achieves", "complete_stronghold", 0)
	ini_write_real("achieves", "complete_storage", 0)
	ini_write_real("achieves", "complete_hotel", 0)
	ini_write_real("achieves", "complete_forest", 0)
	ini_write_real("achieves", "complete_game", 0)
	ini_write_real("achieves", "complete_fast", 0)
	ini_write_real("achieves", "complete_hard", 0)
	ini_write_real("achieves", "complete_hardfast", 0)
	ini_write_real("achieves", "complete_endless", 0)
	ini_write_real("achieves", "complete_somemods", 0)
	ini_write_real("achieves", "complete_allmods", 0)
	ACHIEVE_death_manimo = ini_read_real("achieves", "death_manimo", 0)
	ACHIEVE_death_valerix = ini_read_real("achieves", "death_valerix", 0)
	ACHIEVE_death_mathi = ini_read_real("achieves", "death_mathi", 0)
	ACHIEVE_death_sports = ini_read_real("achieves", "death_sports", 0)
	ACHIEVE_death_ava = ini_read_real("achieves", "death_ava", 0)
	ACHIEVE_death_pravi = ini_read_real("achieves", "death_pravi", 0)
	ACHIEVE_death_joetube = ini_read_real("achieves", "death_joetube", 0)
	ACHIEVE_death_dj = ini_read_real("achieves", "death_dj", 0)
	ACHIEVE_death_jesse = ini_read_real("achieves", "death_jesse", 0)
	ACHIEVE_death_lydia = ini_read_real("achieves", "death_lydia", 0)
	ACHIEVE_death_a90 = ini_read_real("achieves", "death_a90", 0)
	ACHIEVE_complete_attic = ini_read_real("achieves", "complete_attic", 0)
	ACHIEVE_complete_wheatfield = ini_read_real("achieves", "complete_wheatfield", 0)
	ACHIEVE_complete_stronghold = ini_read_real("achieves", "complete_stronghold", 0)
	ACHIEVE_complete_storage = ini_read_real("achieves", "complete_storage", 0)
	ACHIEVE_complete_hotel = ini_read_real("achieves", "complete_hotel", 0)
	ACHIEVE_complete_forest = ini_read_real("achieves", "complete_forest", 0)
	ACHIEVE_complete_game = ini_read_real("achieves", "complete_game", 0)
	ACHIEVE_complete_fast = ini_read_real("achieves", "complete_fast", 0)
	ACHIEVE_complete_hard = ini_read_real("achieves", "complete_hard", 0)
	ACHIEVE_complete_hardfast = ini_read_real("achieves", "complete_hardfast", 0)
	ACHIEVE_complete_endless = ini_read_real("achieves", "complete_endless", 0)
	ACHIEVE_complete_somemods = ini_read_real("achieves", "complete_somemods", 0)
	ACHIEVE_complete_allmods = ini_read_real("achieves", "complete_allmods", 0)
	ini_close()
	room_goto(MENU_achieve)
}